### ISSUE TITLE
Selecting the profile to use

### ISSUE THREAD

**Issue by mjsobrep** [aws-robotics/tts-ros1#18]
I can't figure out how to select the profile to use. As long as my default profile can do what is needed, the system works. 

It seems like the profile could be set here: https://github.com/aws-robotics/tts-ros1/blob/23e7aa554e7c4717de15fbf6c28dd090b3cb89df/tts/src/tts/amazonpolly.py#L198 .

It would be great to be able to just load in a rosparam to do that.

**Comment by ryanewel** [comment]
Hi @mjsobrep,

In general the AWS SDK looks through a series of location for which profile to use. For boto3 the order can be found [here](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuration).
Have you tried setting the ```AWS_PROFILE``` environment variable or are you looking specifically for a ROS-based way to select the profile?

**Comment by mjsobrep** [comment]
I hadn't thought of using that. The environment variable works, and by putting an `env` tag in my launch files, I can set it in a ROS way. So I am satisfied with that. Thanks!
