### ISSUE TITLE
integration_tests don't seem to run

### ISSUE THREAD

**Issue by mjsobrep** [aws-robotics/tts-ros1#37]
It appears as if the integration tests aren't being run when running colcon's test function. That seems to be causing code coverage problems. The other two test sets (test_unit_polly and test_unit_synthesizer) seem to run just fine. I don't really understand colcon enough to know why this is.

**Comment by mm318** [comment]
Hi @mjsobrep, the integration tests weren't intended to run with `colcon test`, like the way the unit tests are. The integration tests never contributed to the code coverage.

There are some additional environment settings needed in order for the integration tests to run successfully. We will improve our documentation to indicate how the integration tests should be run.

**Comment by mjsobrep** [comment]
@mm318 I see, thanks for the clarification. I was having trouble in #36 with getting code coverage with only the unit tests. I'll have to dig deeper to figure out how to do that.

**Comment by AAlon** [comment]
Closing this as no further action is warranted.
